---
# Upcoming Shows
upcoming:
  - date: June 18, 2015
    title: Departure Tour
    venue: Tennyson's Tap
    url: https://www.facebook.com/events/454599778045587/
    datetime: 2015-06-18
    image: 'shows/troy-petty.jpg'
    feature: True
    with:
      - name: Troy Petty
        url: http://www.troypettymusic.com
      - name: Signal Down
        url: http://signaldown.net/

  - date: June 9, 2015
    title: The Holes They Leave [EP Release]
    url: http://www.hi-dive.com/event/864133-teacup-gorilla-denver/
    venue: Hi Dive
    venue_url: http://www.hi-dive.com/
    datetime: 2015-07-09
    image: 'shows/hidive.jpg'
    with:
      - name: Bad Luck City
        url: https://www.facebook.com/badluckcity
      - name: Coastal Wives
        url: https://www.facebook.com/Coastalwives

  - date: August 2, 2015
    title: Wichita, KS
    venue: Kirby's Beer Store
    venue_url: http://www.kirbysbeerstore.com/
    datetime: 2015-08-02
    image: 'shows/kirbys-tour.jpg'

  - date: August 3, 2015
    title: Lawrence, KS
    venue: Eighth Street Taproom
    venue_url: http://eighthstreettaproom.com/
    datetime: 2015-08-03
    image: 'shows/taproom-tour.jpg'

  - date: August 4, 2015
    title: St. Louis, MO
    datetime: 2015-08-04
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 5, 2015
    title: Kansas City, MO
    datetime: 2015-08-05
    image: 'shows/the-brick.jpg'

  - date: August 6, 2015
    title: Duluth, MN
    datetime: 2015-08-06
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 7, 2015
    title: Chicago, IL
    datetime: 2015-08-07
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 8, 2015
    title: Goshen, IN
    datetime: 2015-08-08
    image: 'shows/goshen.jpg'

  - date: August 9, 2015
    title: Grand Rapids, MI
    datetime: 2015-08-09
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 10, 2015
    title: Milwaukee, WI
    datetime: 2015-08-10
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 11, 2015
    title: Iowa City, IA
    datetime: 2015-08-11
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 12, 2015
    title: Omaha, NE
    datetime: 2015-08-12
    image: 'shows/sidesaddle-cover.jpg'

  - date: August 13, 2015
    title: Lincoln, NE
    datetime: 2015-08-13
    image: 'shows/sidesaddle-cover.jpg'


# Recent Shows
recent:
  - date: May 11, 2015
    venue: Gypsy House Cafe
    url: https://www.facebook.com/events/1438931603085393/
    venue_url: https://www.facebook.com/GypsyHouse
    datetime: 2015-05-11
    image: 'shows/walkbysea.jpg'
    with:
      - name: Brennan Mackey (King Cardinal)
        url: https://www.facebook.com/KingCardinalmusic
      - name: Walk by Sea
        url: https://www.facebook.com/walkbysea

  - date: Apr. 17, 2015
    venue: Merchant's Mile High Saloon
    venue_url: http://facebook.com/MerchantsMileHighSaloon
    datetime: 2015-04-17
    image: 'nouns/150402-sidesaddle/affair-12.jpg'
    with:
      - name: Black Market Translation
        url: http://www.blackmarkettranslation.com/
      - name: Tom Waits For No Man
        url: http://tomwaitsfornoman.com/
      - name: Open to the Hound
        url: http://www.opentothehound.com

  - date: Apr. 2, 2015
    title: Riding SideSaddle* [Novel Affair]
    url: http://ridingsidesaddle.net/
    venue: Syntax Physic Opera
    venue_url: http://physicopera.com/
    datetime: 2015-04-02
    image: 'nouns/150402-sidesaddle/affair-18.jpg'
    with:
      - name: Jen Korte
        url: http://jkandtheloss.com
      - name: Open to the Hound
        url: http://www.opentothehound.com

  - date: Jan. 24, 2015
    title: Gorilla Hound Party
    url: https://www.facebook.com/events/978753592154777/
    venue: The Bakery
    venue_url: http://www.thebakerydenver.com/
    datetime: 2015-01-24
    image: 'shows/OttH_TCG.jpg'
    with:
      - name: Open to the Hound
        url: http://www.opentothehound.com

  - date: Jan. 09, 2015
    title: Denver Indie/Alt Fest
    venue: Merchant's Mile High Saloon
    url: http://facebook.com/MerchantsMileHighSaloon
    datetime: 2015-01-09
    with:
      - name: Lucid Vigilantes
        url: facebook.com/LucidVigilantes
      - name: Blind Tomorrow
        url: facebook.com/BlindTomorrow
      - name: 3Piece Special
        url: http://facebook.com/3PieceSpecial

  - date: Nov. 29, 2014
    venue: Larimer Lounge
    url: http://www.larimerlounge.com/event_details.cfm?blogid=1499
    datetime: 2014-11-29
    with:
      - name: The Truth & Spectacle
        url: https://www.facebook.com/thetruthandspectacle
      - name: Cutlass
        url: https://www.facebook.com/cutlasstracks
      - name: Reverb and The Verse
        url: https://www.facebook.com/ReverbandTheVerse

  - date: Nov. 9, 2014
    venue: Lion's Lair
    url: http://www.lionslairlounge.com/events/
    datetime: 2014-11-09
    with:
      - name: See-You-Home-Wolf
        url: http://see-you-home-wolf.bandcamp.com/
      - name: Drunkin Relatives

  - date: Aug. 23, 2014
    venue: Pikes Peak Brewing Co.
    url: http://pikespeakbrewing.com/
    datetime: 2014-08-23
    with:
      - name: Millican
        url: https://soundcloud.com/a-millican

  - date: July 5, 2014
    title: 'Mile High Erotic Spoken Word (#4)'
    venue: 'The&nbsp;Bakery'
    url: http://www.thebakerydenver.com/4th-mile-high-erotic-spoken-word-amurika/
    datetime: 2014-07-05

  - date: May 17, 2014
    title: Bouldering Poets Two Year Anniversary
    url: http://boulderingpoets.wordpress.com/2014/04/07/may-17-2014-two-year-anniversary/
    datetime: 2014-05-17
    with:
      - name: Alan Mudd
      - name: Chris Shugrue
        url: http://twocrowsonawire.blogspot.com/

  - date: Apr. 5, 2014
    venue: Pikes Peak Brewing Co.
    url: http://pikespeakbrewing.com/fall-music-schedule-updated-november-19th/
    datetime: 2014-04-05
    with:
      - name: The Truth & Spectacle
        url: http://thetruthandspectacle.com/

  - date: Jan. 29, 2014
    venue: Larimer Lounge
    url: https://www.facebook.com/events/352732091534807
    datetime: 2014-01-29
    with:
      - name: Arthur Lawrence
        url: http://www.reverbnation.com/arthurlawrence
      - name: Black Wool
        url: http://blackwool.bandcamp.com

  - date: Nov. 16, 2013
    title: Bad Shadow Affair
    venue: Lost Lake Lounge
    url: http://badshadowaffair.blogspot.com/2013/11/november-16th-douglas-cook-meyer.html
    datetime: 2013-11-16
    with:
      - name: Marcia Douglas
      - name: Matt Cook

  - date: Oct. 24, 2013
    venue: Toad Tavern
    url: http://toadtavern.com/?tribe_events=current-youth-johny-got-roxx-timothy-lee-houston-band-tea-cup-gorilla
    datetime: 2013-10-24
    with:
      - name: Current Youth
        url: https://www.facebook.com/currentyouth1
      - name: Johny Got Roxx
        url: https://www.facebook.com/pages/Johnny-Got-Rox/386241998134260
      - name: Timothy Lee Houston Band

  - date: Sept. 30, 2013
    venue: Larimer Lounge
    url: http://www.larimerlounge.com/event_details.cfm?blogid=1278
    datetime: 2013-09-30
    with:
      - name: Evan Holm Band
        url: https://www.facebook.com/EvanHolmDenver
      - name: Mark Risius
        url: https://www.facebook.com/pages/Mark-Risius-Music/209451469137272

  - date: Sept. 19, 2013
    venue: Herman’s Hideaway
    url: http://www.hermanshideaway.com/
    datetime: 2013-09-19
    with:
      - name: 'Nikol&Zack'
        url: http://www.ourstage.com/epk/nikolzack/
      - name: Blame Gravity
        url: http://www.blamegravity.com/
      - name: Lindsey Saunders Band
        url: http://lindseysaundersmusic.com/

  - date: July 27, 2013
    venue: Zach’s Garage
    datetime: 2013-07-27
    with:
      - name: Muscle Beach
        url: https://www.facebook.com/musclebeachparty
      - name: '[empty brackets]'

  - date: March 22, 2013
    title: Bouldering Poets
    url: http://boulderingpoets.wordpress.com/2013/02/
    venue: 303 Vodka
    venue_url: http://303vodka.com/
    datetime: 2013-03-22
    with:
      - name: Georgia Van Gunten
        url: http://naropa.digication.com/GeorgiaVangunten
      - name: Ellen Orleans
        url: http://www.corvidwriters.org/ellen/index.html
      - name: Asalott
        url: http://asalott.com/

  - date: July 21, 2012
    title: 'Leon Presents a Reading Series #6'
    url: https://www.facebook.com/leongallery
    datetime: 2012-07-21
    with:
      - name: Eric Suzanne
        url: http://ericsuzanne.com/
      - name: Kelly Dulaney

  - date: Sept 3, 2010
    venue: Butterfly Pavilion
    datetime: 2010-09-03
    with:
      - name: Rachel Eisenstat
        url: http://www.ravenjane.com/

  - date: June 26, 2010
    venue: The Packing House
    url: http://www.controlgroupproductions.org/
    datetime: 2010-06-26

  - date: March 25-27, 2010
    title: Missa Populi
    url: http://vicioustrap.com/shows/
    venue: The Packing House
    venue_url: http://www.controlgroupproductions.org/
    datetime: 2010-03-25
    before_with: a collaboration
    with:
      - name: Vicious Trap
        url: http://vicioustrap.com/


# Nouns
nouns:
  - body:
      - video: '<iframe src="https://player.vimeo.com/video/125217583?color=ef3939&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
      - image: 'nouns/150402-sidesaddle/affair-18.jpg'
      - image: 'nouns/150402-sidesaddle/affair-15.jpg'
      - image: 'nouns/150402-sidesaddle/affair-10.jpg'
      - image: 'nouns/150402-sidesaddle/affair-9.jpg'
      - video: '<iframe src="https://player.vimeo.com/video/125217582?color=ef3939&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
      - image: 'nouns/150402-sidesaddle/affair-12.jpg'
      - image: 'nouns/150402-sidesaddle/affair-14.jpg'
      - image: 'nouns/150402-sidesaddle/affair-13.jpg'
      - image: 'nouns/150402-sidesaddle/affair-11.jpg'
      - video: '<iframe src="https://player.vimeo.com/video/125222247?color=ef3939&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
      - image: 'nouns/150402-sidesaddle/affair-17.jpg'
      - image: 'nouns/150402-sidesaddle/affair-16.jpg'
      - image: 'nouns/150402-sidesaddle/affair-7.jpg'
      - image: 'nouns/150402-sidesaddle/affair-8.jpg'
      - image: 'nouns/150402-sidesaddle/affair-1.jpg'
        class: full
      - image: 'nouns/150402-sidesaddle/affair-3.jpg'
      - image: 'nouns/150402-sidesaddle/affair-4.jpg'
    caption: '04.15 <a href="http://ridingsidesaddle.net">Riding SideSaddle*</a> Novel Affair'
    citation: 'photos and video by Kenny Storms'
    slug: 'novel-affair'
    feature: true

  - body:
      - video: '<iframe src="http://player.vimeo.com/video/119834636?color=ef3939&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
    caption: '02.15 A Dark Plane — Demo Recording Session'
    citation: 'Words by Gil Scott Heron'
    slug: 'dark-plane-demo'
    feature: true

  - body:
      - video: '<iframe src="http://player.vimeo.com/video/96653953?color=ef3939&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
    caption: '05.14 Bouldering Poets'
    slug: 'bouldering-2'

  - body:
      - video: '<iframe src="http://player.vimeo.com/video/86631301?title=0&amp;byline=0&amp;portrait=0&amp;color=ef3939" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
        class: full
    caption: '01.14 Larimer Lounge'
    citation: 'video by Kenny Storms'
    slug: 'larimerlounge-1'

  - body:
#      - video: '<iframe src="http://player.vimeo.com/video/80691654?title=0&amp;byline=0&amp;portrait=0&amp;color=ef3939" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
#        class: full
      - image: 'nouns/130919-hermans/hermans1.jpg'
      - image: 'nouns/130919-hermans/hermans2.jpg'
      - image: 'nouns/130919-hermans/hermans4.jpg'
        class: full
      - image: 'nouns/130919-hermans/hermans5.jpg'
      - image: 'nouns/130919-hermans/hermans6.jpg'
      - image: 'nouns/130919-hermans/hermans3.jpg'
        class: full
    caption: "09.13 Herman's Hideaway"
    citation: 'video by Megan Sumner :: photos by Kenny Storms'
    slug: 'hermans'
    feature: true

  - body:
      - image: 'nouns/130322-bouldering/bouldering.jpg'
        class: full
      - image: 'nouns/130322-bouldering/bouldering1.jpg'
      - image: 'nouns/130322-bouldering/bouldering2.jpg'
    caption: '03.13 Bouldering Poets'
    citation: 'photos by Elyse Brownell &amp; Christopher Shugrue'
    slug: 'bouldering-1'


# Demo
demo: '<iframe width="100%" height="420" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/9012016&amp;color=ff0000&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>'


# Navigation
nav:
  - url: '/blog/'
    name: blog
  - url: '/verbs/'
    name: shows
  - url: '/nouns/'
    name: media
  - url: '/adjectives/'
    name: bio
  - url: '/press/'
    name: press


# Social Links
social:
  - slug: 'email'
    url: "mailto:info(put the 'at' sign here)teacupgorilla.com"
  - slug: 'twitter'
    url: 'http://twitter.com/teacupgorilla/'
  - slug: 'facebook'
    url: 'http://facebook.com/teacupgorilla/'
  - slug: 'soundcloud'
    url: 'http://soundcloud.com/teacupgorilla/'


# Defaults
title: Teacup Gorilla
author: teacupgorilla
location: home
signup_footer: true


# Meta
copyright: 2015
author_full: Teacup Gorilla
description: "A petite & deadly ground-dwelling band that inhabits the china shops of Denver with angular riffs, twisted stories, and obtuse stomping."
longdesc: "A petite & deadly ground-dwelling band that inhabits the china shops of Denver with angular riffs, twisted stories, and obtuse stomping. Teacup Gorilla has performed in book releases and bars, poetry readings, and hard-core house shows — composed live theatre soundtracks, and founded the The Bakery arts warehouse."
keywords: music, rock, indie, multimedia, poetry, post-rock, art-rock, experimental, denver


# FB
fb_image: 'shows/tg-jen.jpg'
fb_image_width: 1500
fb_image_height: 1000


# Site Config
active_modules: [blog, typogrify, author, wrap]
canonical_url: http://www.teacupgorilla.com/
output_folder: ../../teacupgorilla-pages
template_path: ../templates
modules:
  blog:
    index_url: /blog/
